### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by theodorosploumis** [theodorosploumis/enato_jasonette#1]
- [x] Create a few additional tabs (School History, Photos, Contact).
- [x] Remove unused app permissions.
- [ ] Allow push notifications (for new items, see https://github.com/Jasonette/micropush).
- [ ] Create an official Android App and submit to Google Play.
- [ ] Create an official iOS App and submit to Apple Store.
- [ ] Make it more generic and reusable (eg global variables for links)
- [ ] Create a Drupal 8.x module (rest generator, json mapper, Drupal UI, cli compiler etc)
